spring.application.name=greeting-service
server.port=8080

greeting-service.greeting=Ola
greeting-service.default-name=Mundo

spring.profiles.active=es

management.endpoint.env.show-values=always

spring.config.import=optional:configserver:http://localhost:8888/

#Self Registration Pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka
#Ideal para ambiente containerizados
eureka.instance.prefer-ip-address=true
#Personalizar o Id de cada instância
eureka.instance.instance-id=${spring.application.name}:${server.port}
#Indicar que o Service Registry deve validar a saúde do serviço através do actuator, e não somente Heartbeat
#Opcional - Valor Default = TRUE
eureka.client.healthcheck.enabled=true

#Configuração mínima para atuação com o Service Registry de forma consistente
management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events
#ATENÇÂO: Cuidado ao expor esses dados
#Exibir todas as informações de saúde da aplicação
management.endpoint.health.show-details=always
#Exibir informações no endpoint /actuator/info
management.info.env.anabled=true

#Personalização de informações do endpoint /actuator/info
info.app.name=${spring.application.name}
info.app.description=Greeting Microservice
info.app.autor=Caio Stachelski

#Personalização de Metadatas para o Eureka Service Registry
eureka.instance.metadata-map.github.repo=Stachelski/microservices-java

#Definir a utilização das Probes Liveness = exibição de informações de componentes diversos
#Opcional: Padrão já é TRUE
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true
management.info.env.enabled=true